// <auto-generated />
using System;
using CleanArchitectureSample.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CleanArchitectureSample.Persistence.EF.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20200714140624_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CleanArchitectureSample.Domain.Entities.Attatchment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("Attatchment");
                });

            modelBuilder.Entity("CleanArchitectureSample.Domain.Entities.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("CleanArchitectureSample.Domain.Entities.PackageConfigFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageConfigFile");
                });

            modelBuilder.Entity("CleanArchitectureSample.Domain.Entities.Terminal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Tid")
                        .HasColumnName("TID")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Terminal");
                });

            modelBuilder.Entity("CleanArchitectureSample.Domain.Entities.TerminalPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<int?>("TerminalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("TerminalId");

                    b.ToTable("TerminalPackage");
                });

            modelBuilder.Entity("CleanArchitectureSample.Domain.Entities.Attatchment", b =>
                {
                    b.HasOne("CleanArchitectureSample.Domain.Entities.Package", "Package")
                        .WithMany("Attatchments")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_Attatchment_Package");
                });

            modelBuilder.Entity("CleanArchitectureSample.Domain.Entities.PackageConfigFile", b =>
                {
                    b.HasOne("CleanArchitectureSample.Domain.Entities.Package", "Package")
                        .WithMany("PackageConfigFiles")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_PackageConfigFile_Package");
                });

            modelBuilder.Entity("CleanArchitectureSample.Domain.Entities.TerminalPackage", b =>
                {
                    b.HasOne("CleanArchitectureSample.Domain.Entities.Package", "Package")
                        .WithMany("TerminalPackages")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_TerminalPackage_Package");

                    b.HasOne("CleanArchitectureSample.Domain.Entities.Terminal", "Terminal")
                        .WithMany("TerminalPackages")
                        .HasForeignKey("TerminalId")
                        .HasConstraintName("FK_TerminalPackage_Terminal");
                });
#pragma warning restore 612, 618
        }
    }
}
